create table Asentamiento (idAsentamiento decimal(19,2) generated by default as identity, nombreAsentamiento varchar(255), idCodigoPostal integer, idTipoAsentamiento smallint, primary key (idAsentamiento))
create table CodigoPostal (idCodigoPostal integer generated by default as identity, numeroCodigo varchar(255), idMunicipio integer, primary key (idCodigoPostal))
create table EntidadFederativa (idEntidadFederativa smallint generated by default as identity, nombreEntidadFederativa varchar(255), primary key (idEntidadFederativa))
create table Municipio (idMunicipio integer generated by default as identity, nombreMunicipio varchar(255), idEntidadFederativa smallint, idPlaza smallint, primary key (idMunicipio))
create table Plaza (idPlaza smallint generated by default as identity, nombrePlaza varchar(255), primary key (idPlaza))
create table TipoAsentamiento (idTipoAsentamiento smallint generated by default as identity, nombreTipo varchar(255), primary key (idTipoAsentamiento))
create table TipoEstablecimiento (idTipoEstablecimiento smallint generated by default as identity, nombreTipo varchar(255), primary key (idTipoEstablecimiento))
alter table Asentamiento add constraint FK_g2bdvcemkecn7ecv3uii7i2ym foreign key (idCodigoPostal) references CodigoPostal
alter table Asentamiento add constraint FK_6aknuhg6gk8vdug8m2cujon1e foreign key (idTipoAsentamiento) references TipoAsentamiento
alter table CodigoPostal add constraint FK_qkcu41fplmsxc1krljxw9jka2 foreign key (idMunicipio) references Municipio
alter table Municipio add constraint FK_fyv1472fwhb39ylym1qj0a23h foreign key (idEntidadFederativa) references EntidadFederativa
alter table Municipio add constraint FK_23bxkcy0r5l5b3g2jg93kw6x1 foreign key (idPlaza) references Plaza
